### ISSUE TITLE
Pick a UI framework

### ISSUE THREAD

**Issue by spacekookie** [baubit/Programming-App#3]
Gtk? Qt? Some OpenGL game-thing that can be compiled to run on a phone/ laptop/ potato?

**Comment by IGBC** [comment]
I will leave my ego out of this decision as I haven't worked with any of the tools in quite some time. I will however mention that I have been told that Qt has gotten its shit together recently on the QML side of things. 

Whatever we end up using I can adapt to. Just please not the DOM.
